version: "3.8"

services:
  db:
    image: postgres:14
    container_name: container_clinic_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clinic_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container_clinic_api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Variáveis lidas em src/database/data-source.ts via dotenv
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: clinic_db
      PORT: 3000
    ports:
      - "3000:3000"
    # Para dev com hot‐reload, monte o volume e use ts-node-dev
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

volumes:
  db_data:
    driver: local
